# OpenCodeBlock an open-source tool for modular visual programing in python
# Copyright (C) 2021 Math√Øs FEDERICO <https://www.gnu.org/licenses/>

name: Python coverage

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-tk python3-dev
        sudo apt-get install xvfb
        sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0

        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        touch /home/runner/.Xauthority

    - name: Build unit coverage using pytest-cov
      run: |
        pytest --cov=opencodeblocks --cov-report=xml tests/unit
        score=$(python coverage_score.py --score)
        color=$(python coverage_score.py --color)
        echo "COVERAGE_UNIT_SCORE=$score"
        echo "COVERAGE_UNIT_COLOR=$color"
        echo "COVERAGE_UNIT_SCORE=$score" >> $GITHUB_ENV
        echo "COVERAGE_UNIT_COLOR=$color" >> $GITHUB_ENV
    - name: Create unit coverage badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 00ce73155619a4544884ca6d251954b3
        filename: opencodeblocks_unit_coverage_badge.json
        label: Unit coverage
        message: ${{ env.COVERAGE_UNIT_SCORE }}
        color: ${{ env.COVERAGE_UNIT_COLOR }}
        style: plastic
    - name: Build integration coverage using pytest-cov
      run: |
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1080x24 -ac +extension GLX

        pytest -s --cov=opencodeblocks --cov-report=xml tests/integration
        score=$(python coverage_score.py --score)
        color=$(python coverage_score.py --color)
        echo "COVERAGE_INTEGRATION_SCORE=$score"
        echo "COVERAGE_INTEGRATION_COLOR=$color"
        echo "COVERAGE_INTEGRATION_SCORE=$score" >> $GITHUB_ENV
        echo "COVERAGE_INTEGRATION_COLOR=$color" >> $GITHUB_ENV
      env:
        DISPLAY: :99
        # QT_DEBUG_PLUGINS: 1 # Uncomment to debug Qt library issues.
    - name: Create integration coverage badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 00ce73155619a4544884ca6d251954b3
        filename: opencodeblocks_integration_coverage_badge.json
        label: Integration coverage
        message: ${{ env.COVERAGE_INTEGRATION_SCORE }}
        color: ${{ env.COVERAGE_INTEGRATION_COLOR }}
        style: plastic